### ISSUE TITLE
Stable versions needed

### ISSUE THREAD

**Issue by renespeck** [dice-group/RAKI-Drill-Endpoint#2]
Hi, 

in some projects this endpoint is used. To keep the projects running, stable versions of this endpoint are needed. This current version seems to be depended on  the Github repo of the ontolearn develop branch which gives a runtime error (issue #1).
See:
https://github.com/dice-group/RAKI-Drill-Endpoint/blob/86cb3ec1c7fabf7d91f474c57f4b980ddfca469f/Dockerfile#L9

A stable version of the commit 86cb3ec1c7fabf7d91f474c57f4b980ddfca469f and of the current version is needed to keep the projects depended on this endpoint running. 

Thanks.

**Comment by Demirrr** [comment]
Hello @renespeck,
 
It seems that new changes in ontolearn broke our endpoint. [Following your suggestions](https://github.com/dice-group/RAKI-Drill-Endpoint/commit/19a1628d67d11915f15ee3346be39515a4b473d7) worked like a charm. Please close the open issues after your validation
